# Generated by Django 3.0.6 on 2020-05-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metahumans', '0004_metahuman_ally'),
    ]

    operations = [
        migrations.AddField(
            model_name='metahuman',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
