# Generated by Django 3.0.6 on 2020-05-05 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metahumans', '0006_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='metahuman',
            name='team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='metahumans.Team'),
        ),
    ]
